<template>

  <div class="panel_list">
    <!-- 检索条件 -->
    <Card class="vue-panel">
      <p
        slot="title"
        @click="showPanel=!showPanel"
      >
        <Icon :type="!showPanel?'chevron-down':'chevron-up'"></Icon>
        检索条件
        <router-link to="/demo/demo_desc">
          <Button
            class="fr vue-back-btn header-btn"
            type="primary"
            size="small"
          >详情</Button>
        </router-link>
      </p>
      <Form
        v-if="!showPanel"
        ref="formItem"
        :model="formItem"
        :label-width="95"
        :rules="ruleValidate"
      >
        <Row>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            span="6"
            label="案件状态:"
            prop="caseHandleStatus"
          >
            <Select
              size="small"
              placeholder="请选择案件状态"
              v-model="formItem.caseHandleStatus"
            >
              <Option
                v-for="item in productLineList"
                :value="item.value"
                :key="item.value"
              >{{ item.label }}</Option>
            </Select>
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            span="6"
            label="产品线:"
            prop="prdTyp"
          >
            <Select
              size="small"
              placeholder="请选择产品线"
              v-model="formItem.prdTyp"
            >
              <Option
                v-for="item in productLineList"
                :value="item.value"
                :key="item.value"
              >{{ item.label }}</Option>
            </Select>
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            span="6"
            label="产品期数:"
            prop="perdCnt"
          >
            <Select
              size="small"
              placeholder="请选择产品期数"
              v-model="formItem.perdCnt"
            >
              <Option
                v-for="item in productLineList"
                :value="item.value"
                :key="item.value"
              >{{ item.label }}</Option>
            </Select>
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            label="客户姓名:"
            prop="userNm"
          >
            <Input
              size="small"
              clearable
              v-model="formItem.userNm"
              placeholder="请输入客户姓名"
            />
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            label="身份证号:"
            prop="idNo"
          >
            <Input
              size="small"
              clearable
              v-model="formItem.idNo"
              placeholder="请输入身份证号"
            />
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            label="手机号:"
            prop="mblNo"
          >
            <Input
              size="small"
              clearable
              v-model="formItem.mblNo"
              placeholder="请输入手机号"
            />
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            label="逾期天数:"
            prop="overdueDays"
          >
            <Col
              :xs="11"
              :sm="11"
              :md="11"
              :lg="11"
              span="11"
            >
            <Input
              size="small"
              v-model="formItem.overdueDaysLt"
            ></Input>
            </Col>
            <Col
              :xs="2"
              :sm="2"
              :md="2"
              :lg="2"
              span="2"
            >
            <div class="text-center">-</div>
            </Col>
            <Col
              :xs="11"
              :sm="11"
              :md="11"
              :lg="11"
              span="11"
            >
            <Input
              size="small"
              v-model="formItem.overdueDaysBt"
            ></Input>
            </Col>
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            label="逾期应还金额:"
            prop="device_id"
          >
            <Col
              :xs="11"
              :sm="11"
              :md="11"
              :lg="11"
              span="11"
            >
            <Input
              size="small"
              v-model="formItem.billOvduAmtLt"
            ></Input>
            </Col>
            <Col
              :xs="2"
              :sm="2"
              :md="2"
              :lg="2"
              span="2"
            >
            <div class="text-center">-</div>
            </Col>
            <Col
              :xs="11"
              :sm="11"
              :md="11"
              :lg="11"
              span="11"
            >
            <Input
              size="small"
              v-model="formItem.billOvduAmtBt"
            ></Input>
            </Col>
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            label="案件编号:"
            prop="caseNo"
          >
            <Input
              size="small"
              clearable
              v-model="formItem.caseNo"
              placeholder="请输入案件编号"
            />
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            label="账单号:"
            prop="billNo"
          >
            <Input
              size="small"
              clearable
              v-model="formItem.billNo"
              placeholder="请输入账单号"
            />
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <!-- <FormItem
            span="6"
            label="还款状态:"
            prop="buffet_id"
          >
            <Select
              size="small"
              v-model="formItem.productLine"
            >
              <Option
                v-for="item in productLineList"
                :value="item.value"
                :key="item.value"
              >{{ item.label }}</Option>
            </Select>
          </FormItem> -->
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            span="6"
            label="信用级别:"
            prop="creditLevel"
          >
            <Select
              size="small"
              v-model="formItem.creditLevel"
            >
              <Option
                v-for="item in productLineList"
                :value="item.value"
                :key="item.value"
              >{{ item.label }}</Option>
            </Select>
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem>
            <Button
              type="primary"
              @click="handleSubmit('formItem')"
              style="width:80px"
              long
              size="small"
            >检索</Button>
            <Button
              size="small"
              type="ghost"
              style="width:80px;margin-left: 8px"
              @click="clearForm('formItem')"
            >重置</Button>
          </FormItem>
          </Col>
        </Row>
      </Form>
    </Card>
    <!-- 检索结果 -->
    <Card class="vue-panel-table">
      <p
        slot="title"
        @click="showPanel2=!showPanel2"
      >
        <Icon :type="!showPanel2?'chevron-down':'chevron-up'"></Icon>
        检索结果
        <router-link to="/buffet/buffet_add">
          <Button
            class="fr vue-back-btn header-btn"
            type="primary"
            size="small"
          >导出数据</Button>
        </router-link>
      </p>
      <!-- 表格 -->

      <div v-if="!showPanel2">
        <Table
          :data="tableData"
          :columns="tableColumns"
          stripe
        ></Table>
        <!-- 分页 -->
        <div class="vue-panel-page">

          <div style="float: right;">
            <Page
              :total="total"
              show-total
              size="small"
              :page-size-opts="[10, 20, 50, 100]"
              show-elevator
              show-sizer
              :page-size="pageSize"
              :current="pageNo"
              @on-page-size-change="changeSize"
              @on-change="changePage"
            ></Page>
          </div>

        </div>
      </div>
    </Card>
  </div>
</template>
<script src="./index.js"></script>
