<template>
  <div>
    <Modal
      class="gongzuoliu"
      width="90%"
      v-model="model.modal"
      @on-ok="handleSubmit"
      title="工作流定义"
      @on-visible-change="closeModal"
    >
      <div class="alert-title">基本信息</div>
      <div class="alert-desc">
        <div class="panel-desc">
          <Form
            ref="domain"
            :model="domain"
            :label-width="100"
            class="panel_list"
            :rules="ruleValidate"
          >
            <Row>
              <Col
                :xs="24"
                :sm="24"
                :md="12"
                :lg="12"
                span="12"
              >
              <FormItem
                span="6"
                label="工作流名称:"
                prop="defName"
              >
                <Input
                  size="small"
                  clearable
                  v-model="domain.defName"
                  placeholder="请输入工作流名称"
                ></Input>
              </FormItem>
              </Col>

              <Col
                :xs="24"
                :sm="24"
                :md="12"
                :lg="12"
                span="12"
              >
              <FormItem
                label="驳回类型:"
                prop="backType"
              >
                <Select
                  size="small"
                  placeholder="请选择驳回类型"
                  v-model="domain.backType"
                >
                  <Option
                    v-for="item in backTypeList"
                    :value="item.itemCode"
                    :key="item.itemCode"
                  >{{ item.itemName }}</Option>
                </Select>

              </FormItem>
              </Col>
              <Col
                :xs="24"
                :sm="24"
                :md="12"
                :lg="12"
                span="12"
              >
              <FormItem
                label="工作流类型:"
                prop="defType"
              >
                <Select
                  size="small"
                  placeholder="请选择工作流类型"
                  v-model="domain.defType"
                >
                  <Option
                    v-for="item in defTypeList"
                    :value="item.itemCode"
                    :key="item.itemCode"
                  >{{ item.itemName }}</Option>
                </Select>
              </FormItem>
              </Col>
              <Col
                :xs="24"
                :sm="24"
                :md="12"
                :lg="12"
                span="12"
              >
              <FormItem
                span="6"
                label="工作流编号:"
                prop="defCode"
              >
                <Input
                  size="small"
                  clearable
                  v-model="domain.defCode"
                  placeholder="请输入工作流编号"
                ></Input>
              </FormItem>
              </Col>
              <Col
                :xs="24"
                :sm="24"
                :md="12"
                :lg="12"
                span="12"
              >
              <FormItem
                class="mt5"
                span="6"
                label="描述:"
                prop="defDesc"
              >
                <Input
                  size="small"
                  clearable
                  type="textarea"
                  v-model="domain.defDesc"
                  placeholder="请输入描述"
                ></Input>
              </FormItem>
              </Col>
            </Row>

          </Form>
        </div>
      </div>
      <div class="alert-title">节点信息</div>
      <div class="alert-desc">
        <Row
          type="flex"
          justify="center"
        >
          <Col
            span="24"
            :md="24"
            :lg="24"
            :xs="24"
            :sm="24"
          >
          <Form
            ref="goodsAddForm"
            :rules="rules"
            :model="formData"
            :label-width="120"
          >
            <Row
              class="panel_list border-sh"
              :key="index"
              v-for="(item,index) in formData.items"
            >
              <Icon
                v-if="item.nodeSort!=='51'&&item.nodeSort!=='0'"
                @click="handleDel(index)"
                type="close-circled border-sh-icon"
              ></Icon>
              <Col
                span="12"
                :md="12"
                :lg="12"
                :xs="12"
                :sm="12"
              >
              <FormItem
                label="节点名称"
                :prop="`items.${index}.nodeName`"
              >
                <Input
                  clearable
                  v-model="item.nodeName"
                  type="text"
                  size="small"
                  placeholder="请输入节点名称"
                ></Input>
              </FormItem>
              </Col>
              <Col
                span="12"
                :md="12"
                :lg="12"
                :xs="12"
                :sm="12"
              >
              <FormItem
                :prop="`items.${index}.nodeDesc`"
                label="节点描述"
              >
                <Input
                  type="text"
                  clearable
                  v-model="item.nodeDesc"
                  size="small"
                  placeholder="请输入节点描述"
                ></Input>
              </FormItem>
              </Col>
              <Col
                span="12"
                :md="12"
                :lg="12"
                :xs="12"
                :sm="12"
              >
              <FormItem
                :prop="`items.${index}.nodeCode`"
                label="节点编号"
              >
                <Input
                  clearable
                  v-model="item.nodeCode"
                  type="text"
                  size="small"
                  placeholder="请输入节点编号"
                ></Input>
              </FormItem>
              </Col>
              <Col
                span="12"
                :md="12"
                :lg="12"
                :xs="12"
                :sm="12"
              >
              <FormItem
                :prop="`items.${index}.nodeDealUserId`"
                label="节点处理人ID"
              >
                <Input
                  type="text"
                  clearable
                  v-model="item.nodeDealUserId"
                  size="small"
                  placeholder="请输入节点处理人ID"
                ></Input>
              </FormItem>
              </Col>
              <Col
                span="12"
                :md="12"
                :lg="12"
                :xs="12"
                :sm="12"
              >
              <FormItem
                :prop="`items.${index}.nodeDealName`"
                label="处理人姓名"
              >
                <Input
                  type="text"
                  clearable
                  v-model="item.nodeDealName"
                  size="small"
                  placeholder="请输入处理人姓名"
                ></Input>
              </FormItem>
              </Col>
              <Col
                span="12"
                :md="12"
                :lg="12"
                :xs="12"
                :sm="12"
              >
              <FormItem
                label="节点顺序"
                :prop="`items.${index}.nodeSort`"
              >
                <Input
                  style="width:100%"
                  v-model="item.nodeSort"
                  :disabled="index===0||index===1"
                  placeholder="请输入节点顺序"
                  size="small"
                ></Input>
                <!-- <Input
                  type="text"
                  clearable
                  
                  size="small"
                ></Input> -->
              </FormItem>
              </Col>

            </Row>
            <FormItem class="mt10">
              <Col span="12">
              <Button
                type="dashed"
                long
                @click="handleAdd"
                icon="plus-round"
              >添加节点</Button>
              </Col>
            </FormItem>
          </Form>
          </Col>
        </Row>
      </div>
      <div slot="footer">
        <Button
          type="ghost"
          size="small"
          @click="del"
        >关闭</Button>
        <Button
          type="primary"
          size="small"
          @click="handleSubmit('formItem')"
          v-if="model.type !== '1'"
        >保存</Button>
      </div>
    </Modal>
  </div>
</template>

<script src="./gongzuoliu.js"></script>

<style lang="less">
@import "./index.less";
</style>
