<template>

  <div class="panel_list">
    <!-- 检索条件 -->
    <Card class="vue-panel">
      <p
        slot="title"
        @click="showPanel=!showPanel"
      >
        <Icon :type="!showPanel?'chevron-down':'chevron-up'"></Icon>
        逾期信息
      </p>
      <Form
        v-if="!showPanel"
        ref="formItem"
        :model="formItem"
        :label-width="80"
        :rules="ruleValidate"
      >
        <Row>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            span="6"
            label="产品线:"
          >
            <label
              class="panel-label"
              for=""
            >2222222</label>
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            span="6"
            label="产品线:"
          >
            <label
              class="panel-label"
              for=""
            >2222222</label>
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            span="6"
            label="产品线:"
          >
            <label
              class="panel-label"
              for=""
            >2222222</label>
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            span="6"
            label="产品线:"
          >
            <label
              class="panel-label"
              for=""
            >2222222</label>
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            span="6"
            label="产品线:"
          >
            <label
              class="panel-label"
              for=""
            >2222222</label>
          </FormItem>
          </Col>

        </Row>
      </Form>
    </Card>
    <!-- 检索条件 -->
    <Card class="vue-panel">
      <p
        slot="title"
        @click="showPanel2=!showPanel2"
      >
        <Icon :type="!showPanel2?'chevron-down':'chevron-up'"></Icon>
        还款信息
      </p>
      <Form
        v-if="!showPanel2"
        ref="formItem"
        :model="formItem"
        :label-width="80"
        :rules="ruleValidate"
      >
        <Row>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            span="6"
            prop="buffet_id"
            label="产品线:"
          >
            <Input
              size="small"
              clearable
              v-model="formItem.buffet_name"
              placeholder="请输入餐柜名称"
            ></Input>
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            span="6"
            label="产品线:"
          >
            <Input
              size="small"
              clearable
              v-model="formItem.buffet_name"
              placeholder="请输入餐柜名称"
            ></Input>
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            span="6"
            label="产品线:"
          >
            <Input
              size="small"
              clearable
              v-model="formItem.buffet_name"
              placeholder="请输入餐柜名称"
            ></Input>
          </FormItem>
          </Col>
           <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            span="6"
            label="产品线:"
          >
            <Input
              size="small"
              clearable
              v-model="formItem.buffet_name"
              placeholder="请输入餐柜名称"
            ></Input>
          </FormItem>
          </Col>
           <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            span="6"
            label="产品线:"
          >
            <Input
              size="small"
              clearable
              v-model="formItem.buffet_name"
              placeholder="请输入餐柜名称"
            ></Input>
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            span="6"
            label="产品线:"
          >
            <Input
              size="small"
              clearable
              v-model="formItem.buffet_name"
              placeholder="请输入餐柜名称"
            ></Input>
          </FormItem>
          </Col>
          <Col
            :xs="24"
            :sm="24"
            :md="6"
            :lg="6"
            span="6"
          >
          <FormItem
            span="6"
            label="产品线:"
          >
            <Input
              type="textarea"
              size="small"
              clearable
              v-model="formItem.buffet_name"
              placeholder="请输入餐柜名称"
            ></Input>
          </FormItem>
          </Col>

        </Row>
        <Row class="panel-desc-btn">
          <Button
            type="primary"
            @click="handleSubmit('formItem')"
            style="width:80px"
            long
            size="small"
          >确认</Button>
          <Button
            size="small"
            type="ghost"
            style="width:80px;margin-left: 8px"
            @click="clearForm('formItem')"
          >返回</Button>
        </Row>
      </Form>
    </Card>
  </div>
</template>
<script src="./index.js"></script>
